### ISSUE TITLE
支持吗 spring boot1  吗

### ISSUE THREAD

**Issue by cckmit** [alibaba/easy-retry#18]
支持吗 spring boot1  吗

**Comment by wangxun520** [comment]
没跟你开玩笑，你fork的某项目涉及重要问题，请尽快联系我并删除，18681947520(微信同号)，尽快联系，不知道你以前是不是DC公司的

> 支持吗 spring boot1 吗

**Comment by iMouseWu** [comment]
> 支持吗 spring boot1 吗
目前仅支持spring boot2，不过可以基于easy-retry-core写一个spring boot1 的starter

**Comment by cckmit** [comment]
DC公司是什么公司啊 fork 还需要是DC公司的才能fork

**Comment by wangxun520** [comment]
离职员工上传国家涉密项目，请再次确认suevip1不是你的账号，不然小心别惹上麻烦了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/easy-retry"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月10日(星期五) 晚上11:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/easy-retry] 支持吗 spring boot1  吗 (Issue #18)





 
DC公司是什么公司啊 fork 还需要是DC公司的才能fork

**Comment by cckmit** [comment]
suevip1 是谁啊 我怎么知道啊

**Comment by wangxun520** [comment]
嗯嗯，不是你的号就好
以后fork工程务必小心谨慎，麻烦了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/easy-retry"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月10日(星期五) 晚上11:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/easy-retry] 支持吗 spring boot1  吗 (Issue #18)





 
suevip1 是谁啊 我怎么知道啊
