### ISSUE TITLE
如何控制重试次数

### ISSUE THREAD

**Issue by cckmit** [alibaba/easy-retry#21]

**Comment by iMouseWu** [comment]
mybatis的可以在application.properties增加配置 使用 spring.easyretry.mybatis.maxRetryTimes来控制
memory的可以在application.properties增加配置 使用 spring.easyretry.memory.maxRetryTimes来控制

**Comment by cckmit** [comment]
可是每个任务的重试次数不一样的啊

**Comment by iMouseWu** [comment]
> 可是每个任务的重试次数不一样的啊
easy-retry是异步去执行重试，所以从全局统一来看的话，我理解是不是全局配置一个值就可以满足诉求了，当然能精细化管理肯定更加好。我们看下能不能在后续的迭代里面增强一下这部分能力
