### ISSUE TITLE
可否增加对 solon 框架的适配？：）

### ISSUE THREAD

**Issue by noear** [alibaba/easy-retry#24]
框架仓库：https://github.com/noear/solon

**Comment by chl1442802633** [comment]
非常有必要适配下  我们目前在使用solon

**Comment by xigexb** [comment]
我们内部几个项目都用到了solon和retry。建议官方适配下。

**Comment by iMouseWu** [comment]
我们看看能不能在下个大版本里面加上对solon的支持。感谢各位的建议

**Comment by noear** [comment]
@iMouseWu 感谢！

**Comment by xigexb** [comment]
在参与其他开源项目，暂时没时间参与该项目的贡献。感谢邀请。

发件人: ***@***.***>
发送时间: 2023年11月9日 18:47
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [alibaba/easy-retry] 可否增加对 solon 框架的适配？：） (Issue #24)


我们看看能不能在下个大版本里面加上对solon的支持。感谢各位的建议

―
